Make FreeBSD, Linux and macOS builds warning-free.
.../libpcap/testprogs/fuzz/fuzz_filter.c:33:9: error: ignoring return
  value of 'pcap_setfilter' declared with attribute 'warn_unused_result'
  [-Werror=unused-result]

Since the warning now reliably fails CMake builds, let's fix it.