Silence -Wsign-compare about musl CMSG_NXTHDR(). [skip appveyor]
Alpine clang version 17.0.5

./pcap-bt-linux.c:373:10: error: comparison of integers of different
  signs: 'unsigned long' and 'long' [-Werror,-Wsign-compare]

./pcap-bt-monitor-linux.c:140:59: error: comparison of integers of
  different signs: 'unsigned long' and 'long' [-Werror,-Wsign-compare]

/usr/include/sys/socket.h:358:44: note: expanded from macro
  'CMSG_NXTHDR'
 __CMSG_LEN(cmsg) + sizeof(struct cmsghdr) >= __MHDR_END(mhdr) -
   (unsigned char *)(cmsg) \

(cherry picked from commit 36d63625cfbf544aa0b6fd4b1e95a299d9822bb8)