Use the correct strerror_r() in pcap.c.
Without ftmacros.h the file does not define _GNU_SOURCE before including
<string.h>, which always results in the XSI-specific strerror_r(), which
is a problem when Autoconf/CMake have detected the GNU-specific
strerror_r() using ftmacros.h.  In the master branch the file already
includes the header by other means.

./pcap.c:3771:16: error: returning 'int' from a function with return
  type 'const char *' makes pointer from integer without a cast
  [-Werror=int-conversion]
 3771 |         return strerror_r(errnum, errbuf, PCAP_ERRBUF_SIZE);