Add missing compiler_state_t parameter
Fix error:

/
|../libpcap-1.8.1/gencode.c: In function 'gen_gateway':
|../libpcap-1.8.1/gencode.c:4914:13: error: 'cstate' undeclared
| (first use in this function)
|    bpf_error(cstate, "direction applied to 'gateway'");
\

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>