build.sh: Add a "clean" before build, useful when used standalone
Do two make commands to avoid an error on osx with "make clean all" and
MAKEFLAGS='-j 2', like:
./gencode.c:67:10: fatal error: 'grammar.h' file not found
#include "grammar.h"
         ^~~~~~~~~~~
1 error generated.
make: *** [gencode.o] Error 1

(cherry picked from commit 3586222ba4a0388cfc88731f82ca046427781a9e)