Address a few compiler warnings on Haiku.
In gencode.c instead of casting pointer types copy the data to squelch 4
previously known warnings from GCC and Clang.  (Oddly enough, Haiku is
the only OS that unconditionally puts a 32-bit array into the union
inside struct in6_addr, yet the only OS where these warnings appeared.)

In pcap.c add a temporary workaround for ioctl() to squelch two other
Clang warnings:

pcap.c:1619:6: error: missing field 'size' initializer
  [-Werror,-Wmissing-field-initializers]
pcap.c:1638:6: error: missing field 'size' initializer
  [-Werror,-Wmissing-field-initializers]

With these changes GCC builds are now warning-free, so in build.sh set
LIBPCAP_TAINTED for Clang only and update the comment to show the
current remaining warnings.

(backported from commit 02b98a948dfb661c3e04fca91bd9485525d4198f)