fix Linux build errors after commit fb20696
Travis CI build was OK but on my Ubuntu 14.04 PC it would fail:

./gencode.c: In function ‘gen_vlan_bpf_extensions’:
./gencode.c:7902:22: error: ‘cstate’ undeclared (first use in this function)
         s = new_stmt(cstate, BPF_LD|BPF_B|BPF_ABS);
                      ^
./gencode.c:7902:22: note: each undeclared identifier is reported only once for each function it appears in
./gencode.c: In function ‘gen_vlan’:
./gencode.c:8015:7: error: ‘off_outermostlinkhdr’ undeclared (first use in this function)
       off_outermostlinkhdr.constant_part) {
       ^
make: *** [gencode.o] Error 1