Fix compiling on Solaris 9.
./optimize.c:2612:22: error: 'SIZE_MAX' undeclared (first use in this
function)

(backported from commit 1f25961a7817174876a044be20082670bbea4fb0)