capturetest: Treat SA_RESTART as optional.
QNX SDP 8.0.3, cross-compiling for AArch64.

./capturetest.c:203:48: error: 'SA_RESTART' undeclared (first use in
  this function); did you mean 'ERESTART'?

(cherry picked from commit 38741edd7175dd26293beb27742e9dd757041fab)