Require config.h to be from the libpcap build.
Port the bug fix from tcpdump commit 9beea81: in case somebody tries to
build libpcap incorrectly, fail at the build time, not at a run time.

In this version of the solution define LIBPCAP_CONFIG_H without a guard
because nothing in config.h uses a guard because in this source tree
config.h is never included more than once under normal circumstances, so
let's not change the status quo.  This way, if LIBPCAP_CONFIG_H has been
irregularly defined before config.h, let the compiler complain about it.

$ mkdir /tmp/testconfig
$ cat >/tmp/testconfig/config.h <<EOF
  #define PACKAGE_VERSION "THIS IS A BUG"
  #define SIZEOF_TIME_T 8
  #define HAVE_SOCKLEN_T 1
  #define HAVE_STRLCPY 1
EOF
$ CFLAGS='-I/tmp/testconfig' ./configure -q

Before:
$ make -s testprogs
$ ./testprogs/versiontest
libpcap version THIS IS A BUG (64-bit time_t, with TPACKET_V3)

After:
$ make -s testprogs
pcap.c:36:2: error: #error "The included config.h header is not from the
  libpcap build."
make: *** [Makefile:84: pcap.o] Error 1