QNX: Use "unix.h" instead of the missing <sysexits.h>.
QNX SDP 8.0.3, cross-compiling for AArch64.

./filtertest.c:43:12: fatal error: sysexits.h: No such file or directory
./translatetest.c:14:12: fatal error: sysexits.h: No such file or
  directory