DAG: Fix building after commit 7dbcae6. [skip ci]
pcap-dag.c:151:42: error: 'p' undeclared (first use in this function);
  did you mean 'ip'?
pcap-dag.c:859:35: error: 'ifacev' undeclared (first use in this
  function); did you mean 'iface'?
pcap-dag.c:844:22: warning: unused variable 'env' [-Wunused-variable]
pcap-dag.c:1137:52: warning: pointer targets in passing argument 2 of
  'get_decuint_from_env' differ in signedness [-Wpointer-sign]
pcap-dag.c:1158:55: warning: pointer targets in passing argument 2 of
  'get_decuint_from_env' differ in signedness [-Wpointer-sign]
pcap-dag.c:951:15: warning: unused variable 's' [-Wunused-variable]