Fix HCI_CHANNEL_MONITOR detection with musl libc.
Alpine Linux v3.19
musl libc (x86_64) version 1.2.4_git20230717

configure: Bluetooth sniffing is supported
checking for struct sockaddr_hci.hci_channel... yes
checking if HCI_CHANNEL_MONITOR is defined... no

-- Looking for bluetooth/bluetooth.h
-- Looking for bluetooth/bluetooth.h - found
-- Performing Test HAVE_STRUCT_SOCKADDR_HCI_HCI_CHANNEL
-- Performing Test HAVE_STRUCT_SOCKADDR_HCI_HCI_CHANNEL - Success
-- Performing Test PCAP_SUPPORT_BT_MONITOR
-- Performing Test PCAP_SUPPORT_BT_MONITOR - Failed

Apparently, the symbol is defined, but the test fails because u_int is
not available by default in musl, with both GCC and Clang:

/usr/include/bluetooth/hci.h:2343:#define HCI_CHANNEL_MONITOR	2

conftest.c:57:45: error: unknown type name 'u_int'; did you mean 'int'?

Use int instead of adding <sys/types.h> to the solution space:

checking if HCI_CHANNEL_MONITOR is defined... yes

-- Performing Test PCAP_SUPPORT_BT_MONITOR
-- Performing Test PCAP_SUPPORT_BT_MONITOR - Success