Silence -Wuninitialized-const-pointer for setsockopt() in valgrindtest.c
Because it is the expected behavior, see #1607.

Clang >= 21.1.0.

Based on Guy diagnostic.

./valgrindtest.c:407:53: error: variable 'bad_fcode' is
      uninitialized when passed as a const pointer argument here
      [-Werror,-Wuninitialized-const-pointer]
  407 |         setsockopt(pcap_fd, SOL_SOCKET, SO_ATTACH_FILTER, &bad_fcode,
      |                                                            ^~~~~~~~~
1 error generated.

(cherry picked from commit 7a8f78b947edd7bf37ccb460df6b6594245402ba)