Fix uintN types on Haiku after hrev57738. [skip ci]
In Haiku <SupportDefs.h> defines int8, int16 and int32; other Haiku
headers used to include <SupportDefs.h> implicitly, but this is not the
case since commit 1834e1256:

./rpcap-protocol.h:145:9: error: unknown type name 'uint8'
./rpcap-protocol.h:146:9: error: unknown type name 'uint8'
./rpcap-protocol.h:147:9: error: unknown type name 'uint16'
./rpcap-protocol.h:148:9: error: unknown type name 'uint32'
(and so on)

In rpcap-protocol.h include the header explicitly on Haiku.