Revert "Tell CMake libpcap is a C-only project (no C++)." [skip ci]
As Francois-Xavier and Guy point it out, it is a C + C++ project on
Haiku.  My change prevented pcap-haiku.cpp (which does not currently
compile) from compiling and subsequently the linking failed:

ld: ../../libpcap.a(pcap.c.o): in function `pcap_findalldevs':
pcap.c:(.text+0x54e): undefined reference to `pcap_platform_finddevs'
ld: ../../libpcap.a(pcap.c.o): in function `pcap_create':
pcap.c:(.text+0x1456): undefined reference to `pcap_create_interface'
collect2: error: ld returned 1 exit status

Revert the change and let the build process fail where the problem is
(at pcap-haiku.cpp).