dlpi: fix an unused variable error
pcap-dlpi.c: In function 'split_dname':
pcap-dlpi.c:959:8: error: unused variable 'eos' [-Werror=unused-variable]
  959 |  char *eos;
      |        ^~~

(found on cfarm210 with gcc)