pcap-bpf: Remove dead code for BSD/OS, which is no longer supported
This also avoids a 'not defined' macro error.

The error was:
./pcap-bpf.c: In function 'pcap_activate_bpf':
./pcap-bpf.c:2334:5: error: "_BSDI_VERSION" is not defined, evaluates
to 0 [-Werror=undef]
 2344 | #if _BSDI_VERSION - 0 >= 199510
      |     ^~~~~~~~~~~~~