QNX: Disable zero-copy BPF to work around portability issues.
QNX SDP 8.0.3, cross-compiling for AArch64.

pcap-bpf.c:126:12: fatal error: machine/atomic.h: No such file or
  directory

(cherry picked from commit ad82dbe382b266d17d02505d84d40b9471e432c7)