Fixup the previous commit.
pcap-types.h is available in the libpcap source tree, but not in the
destination prefix directory, so libpcap builds were fine, but some
tcpdump builds were not:

/tmp/tcpdump_build_matrix.tJGlC8Py/include/pcap/bpf.h:83:10: fatal
  error: pcap-types.h: No such file or directory

Port the contents of pcap-types.h into pcap/bpf.h.

(cherry picked from commit 341acb8f503288ded832d4c5266ce89a2f6e6548)