dpdk: add rte_ prefix to ether definitions
DPDK commits 35b2d13fd6fd ("net: add rte prefix to ether defines")
and 6d13ea8e8e49 ("net: add rte prefix to ether structures") renamed
ETHER_MAX_JUMBO_FRAME_LEN to RTE_ETHER_MAX_JUMBO_FRAME_LEN and struct
ether_addr to struct rte_ether_addr.

Fix the compilation of pcap-dpdk.c, which currently fails with:

    error: ‘ETHER_MAX_JUMBO_FRAME_LEN’ undeclared here (not in a function); did you mean ‘RTE_ETHER_MAX_JUMBO_FRAME_LEN’?
    ...
    error: field ‘eth_addr’ has incomplete type
    ...
    error: dereferencing pointer to incomplete type ‘struct ether_addr’

Signed-off-by: Vivien Didelot <vivien.didelot@gmail.com>