Include <linux/netlink.h> from pcap-linux.c.
Debian 6.0.10, kernel 2.6.32-5-amd64, gcc (Debian 4.4.5-8) 4.4.5.

pcap-linux.c:1710: error: 'NETLINK_GENERIC' undeclared (first use in
  this function)

(cherry picked from commit b0292f18909d8942dc0d89fe90feefcdf0c0cb08)