findalldevstest: Avoid warning/error when IPv6 is not enable
The warning/error was:
./findalldevstest.c:193:8: error: unused variable 'ipv6_buf'
  [-Werror,-Wunused-variable]
  char ipv6_buf[INET6_ADDRSTRLEN];
       ^

(cherry picked from commit 1b5ddac906932f861aabddadd464e6f8a1bec030)