fixed windows cross compile
when cross-compiling this project under Windows, an error occurs "charconv.c:58: error: ‘EINVAL’ undeclared"

(cherry picked from commit 2622c1f053e64f1306b25ba197266cc2048e7fb3)