Make more code cleanups in findalldevstest.c.
As it turns out, my commit ec52439 caused breakage in Windows builds:

findalldevstest.c(335): error C2039: 'sdl_index': is not a member of
  'sockaddr_dl'
findalldevstest.c(336): error C2039: 'sdl_type': is not a member of
  'sockaddr_dl'
findalldevstest.c(337): error C2039: 'sdl_type': is not a member of
  'sockaddr_dl'
findalldevstest.c(337): error C2065: 'IFT_ETHER': undeclared identifier
findalldevstest.c(338): error C2039: 'sdl_alen': is not a member of
  'sockaddr_dl'
findalldevstest.c(343): error C2039: 'sdl_type': is not a member of
  'sockaddr_dl'
findalldevstest.c(343): error C2065: 'IFT_ETHER': undeclared identifier
findalldevstest.c(343): error C2039: 'sdl_alen': is not a member of
  'sockaddr_dl'
findalldevstest.c(343): error C2065: 'ETHER_ADDR_LEN': undeclared
  identifier

As Guy Harris explains, certain versions of Windows define AF_LINK, but
struct sockaddr_dl is different.  Consistently disable all AF_PACKET and
AF_LINK handling code on Windows to fix this.

The INET6 macro controls IPv6-specific features of the filter syntax,
but not the set of address families pcap_findalldevs() can return.  Thus
in ifprint() make the code that prints an AF_INET6 address conditional
on AF_INET6, not INET6.

Ibid., put the short branch of a long if statement first; move some
variables closer to the code that needs them; lose a no-op statement; do
not test whether .addr is not NULL because the entire switch statement
is already conditional on that.

Rewrite mac_addr_str() as ether_ntop() to make printing of AF_PACKET and
AF_LINK more consistent with AF_INET and AF_INET6.